# Generated by Django 3.0.8 on 2020-07-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlocation',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='postmedia',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='postsource',
            name='profile',
        ),
    ]
