# Generated by Django 3.0.7 on 2020-07-07 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say'), ('custom', 'Custom')], default='male', max_length=255, null=True)),
                ('dob', models.CharField(blank=True, default='YYYY-MM-DD', max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=140, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('following', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('loggedIn', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileFollowing',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('following_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_profile', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileFollower',
            fields=[
                ('id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('follower_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profile', to='accounts.UserProfile')),
            ],
        ),
    ]
